config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'bicycles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bicycles do
    resources :bookings, except: [:index]
    get 'bookings', to: 'bookings#bicycle_bookings', as: :bookings_all
  end
  get 'bookings', to: 'bookings#user_bookings', as: :user_bookings

  resources :users, only: [:index] do
    resources :bicycles, only: [:index]
  end

  get 'bicycles-search', to: 'bicycles#search_results'
  get 'no-results', to: 'bicycles#no_results'
  get 'my-bikes', to: 'bicycles#my_bikes'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :price, presence: true, numericality: { only_integer: true }
  validates :photo, presence: true
  validates :brand, presence: true
  validates :model, presence: true
  validates :post_code, presence: true
  validates :description, presence: true
  validates_format_of :post_code, with: /([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))\s?[0-9][A-Za-z]{2})/
  mount_uploader :photo, PhotoUploader

  include PgSearch
  pg_search_scope :search_bikes,
    against: [:model, :brand, :description, :post_code, :area, :price],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bicycle
  validates :date_start, presence: true
  validates :date_end, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bicycles, dependent: :destroy
  has_many :bookings, dependent: :destroy
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end
end

app/controllers/bicycles_controller.rb
require 'open-uri'
require 'json'

class BicyclesController < ApplicationController
  before_action :find_bicycle, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show, :search_results]

  def index
    @bicycles = Bicycle.all
  end

  def show
    @bookings = @bicycle.bookings.where("date_start > ?", Date.today)
    @bookings_array = @bookings.map do |booking|
      { from: booking.date_start.to_s.split(' ')[0], to: booking.date_end.to_s.split(' ')[0]}
    end
    area_by_postcode(@bicycle)
    @booking = Booking.new
  end

  def new
    @bicycle = Bicycle.new
  end

  def create
    @bicycle = Bicycle.new(bicycle_params)
    @bicycle.user = current_user
    @bicycle = lon_and_lat(@bicycle)
    if @bicycle.save
      redirect_to bicycle_path(@bicycle)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @bicycle.update(bicycle_params)
    @bicycle = lon_and_lat(@bicycle)
    if @bicycle.save
      redirect_to bicycle_path(@bicycle)
    else
      render :edit
    end
  end

  def destroy
    @bicycle.destroy
    redirect_to my_bikes_path
  end

  def search_results
    @query = params[:query]
    @bicycles = Bicycle.search_bikes(params[:query])
    map
    redirect_to no_results_path if @bicycles.empty?
  end

  def my_bikes
    @bicycles = Bicycle.where(user: current_user)
  end

  private

  def bicycle_params
    params.require(:bicycle).permit(:brand, :model, :user_id, :post_code, :description, :price, :photo, :longitude, :latitude, :area)
  end

  def find_bicycle
    @bicycle = Bicycle.find(params[:id])
  end

  def lon_and_lat(bicycle)
    url = "https://api.postcodes.io/postcodes/#{@bicycle.post_code.delete(" ")}"
    response = JSON.parse(open(url).read)
    bicycle.latitude = response["result"]["latitude"]
    bicycle.longitude = response["result"]["longitude"]
    bicycle.area = area_by_postcode(bicycle)
    bicycle
  end

  def area_by_postcode(bicycle)
    unless bicycle
      bicycle = Bicycle.find(params[:id])
    end
    url = "https://api.postcodes.io/postcodes/#{bicycle.post_code.delete(" ")}"
    response = JSON.parse(open(url).read)
    response["result"]["admin_district"]
  end

  def map
    @markers = @bicycles.map do |bicycle|
      {
        lng: bicycle.longitude,
        lat: bicycle.latitude,
        infoWindow: { content: render_to_string(partial: "/bicycles/map_window", locals: { bicycle: bicycle }) }
      }
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show, :edit, :update, :destroy]

  # def index
  #   @bookings = Booking.all
  # end

  def show
    calculate_total_price
  end

  def new
    @bicycle = find_bicycle
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.bicycle = find_bicycle
    @booking.user = current_user
    if @booking.save
      redirect_to user_bookings_path
    else
      render :new
    end
  end

  def edit
    @bicycle = find_bicycle
  end

  def update
    @booking.update(booking_params)
    redirect_to bicycle_booking_path(@booking.bicycle, @booking)
  end

  def destroy
    @booking.destroy
    redirect_to user_bookings_path
  end

  def user_bookings
    @bookings = Booking.where(user_id: current_user)
  end

  def bicycle_bookings
    @bookings = Booking.where(bicycle_id: params[:bicycle_id])
  end

  private

  def booking_params
    params.require(:booking).permit(:date_start, :date_end, :user_id, :bicycle_id)
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def find_bicycle
    Bicycle.find(params[:bicycle_id])
  end

  def calculate_total_price
    @price = @booking.bicycle.price * ((@booking.date_end - @booking.date_start) * 0.000277778).floor
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bicycles/_map_window.html.erb
<div class="map-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path bicycle.photo %>);">
  <div class="bicycle-description">
     <h4><%= bicycle.brand.capitalize + " " + bicycle.model.capitalize %></h4>
  </div>
  <div class="bicycle-price">
    <p>£<%= bicycle.price %>/hr</p>
  </div>
  <div class="bicycle-rating">
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star"></span>
  </div>
  <%= link_to "", bicycle_path(bicycle), class: "card-link"%>
</div>

app/views/bicycles/edit.html.erb
<div class="container container-form">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <div class="panel panel-form">
      <div class="header">
      <p>Edit bicycle</p>
      </div>
        <%= simple_form_for @bicycle do |f| %>
        <%= f.input :brand %>
        <%= f.input :model %>
        <%= f.input :post_code, label: "Postcode" %>
        <%= f.input :description, placeholder: "Write a short description of your bike", input_html: { rows: 3 } %>
        <%= f.input :price, label: "Price per hour (£)" %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <label class="form-control-label text optional" for="bicycle_description"></label>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/bicycles/index.html.erb
<%= render 'layouts/components/banner.html.erb' %>
<%= render 'layouts/components/card.html.erb' %>

app/views/bicycles/my_bikes.html.erb
<%= render 'layouts/components/card.html.erb' %>

app/views/bicycles/new.html.erb
<div class="container container-form">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <div class="panel panel-form">
      <div class="header">
        <p>Add a bicycle!</p>
      </div>
      <%= simple_form_for @bicycle do |f| %>
          <%= f.input :brand %>
          <%= f.input :model %>
          <%= f.input :post_code, label: "Postcode" %>
          <%= f.input :description, placeholder: "Write a short description of your bike", input_html: { rows: 3 } %>
          <%= f.input :price, label: "Price per hour (£)" %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <div class="form-group">
            <label class="form-control-label text optional" for="bicycle_description"></label>
            <%= f.submit %>
          </div>
      <% end %>
    </div>

  </div>
</div>

app/views/bicycles/no_results.html.erb
<h1>NO RESULTS :(</h1>

app/views/bicycles/search_results.html.erb
<div class="container">
  <%= render 'layouts/components/search.html.erb' %>
  <br>
  <% if @bicycles.count == 1 %>
    <p class="results-found"><%= @bicycles.count %> result found for "<%= @query %>"</p>
  <% end %>
  <% if @bicycles.count > 1 %>
    <p class="results-found"><%= @bicycles.count %> results found for "<%= @query %>"</p>
  <% end %>
  <div class="search_results_flex">
    <%= render 'layouts/components/card.html.erb' %>
    <div
      id="map"
      style="width: 100%;
      height: 600px;"
      data-markers="<%= @markers.to_json %>"
    ></div>
  </div>
</div>

app/views/bicycles/show.html.erb
<div class="bike_image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path (@bicycle.photo.filename.nil? ? "" : @bicycle.photo) %>);">
</div>
<div class = "container">
  <div class="row" ">
    <div class="col-xs-12 col-md-8">
      <div class = "description_card">
        <h2 class="fix-margin-h2"><strong><%= "#{@bicycle.brand.capitalize} #{@bicycle.model.capitalize}" %></strong></h2>
        <h4><%= @bicycle.area %></h4>
        <p><%= @bicycle.description %></p>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="booking_card" id="booking_dates" data-array="<%= @bookings_array.to_json %>">
        <h2>£<span id="bike_price"><%= @bicycle.price %></span>/hr</h2>
        <div class="rating">
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star"></span>
          <span>(23)</span>
        </div>
        <% unless @bicycle.user == current_user %>
          <%= render 'layouts/components/date_picker.html.erb' %>
        <% end %>
        <% if @bicycle.user == current_user %>
          <%= render 'layouts/components/my_bike.html.erb' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  function getHours() {
    if(document.getElementById("booking_date_end").value) {
      var a = document.getElementById('booking_date_start').value
      var b = document.getElementById('booking_date_end').value
      var milliseconds = ((new Date(a)) - (new Date(b)))
      var minutes = milliseconds/(60000)
      var hours = minutes/(60)
      return hours
    };
  }

  function revealBook() {
    if(document.getElementById("booking_date_end").value && document.getElementById("booking_date_start").value) {
      document.getElementById("book-btn").classList.remove("hidden");
    }
  }

  var date_end = document.getElementById("booking_date_end")
  var date_start = document.getElementById("booking_date_start")
  date_end.addEventListener("input", (event) => {
    revealBook();
  });

  var price = document.getElementById("bike_price").innerHTML
  date_start.addEventListener("input", (event) => {
        if(document.getElementById("booking_date_end").value && document.getElementById("booking_date_start").value) {
          document.getElementById("total-price").innerHTML = -(getHours() * price);
          document.getElementById("currency").classList.remove("hidden");
        }
      });
  date_end.addEventListener("input", (event) => {
        if(document.getElementById("booking_date_end").value && document.getElementById("booking_date_start").value) {
          document.getElementById("total-price").innerHTML = -(getHours() * price);
          document.getElementById("currency").classList.remove("hidden");
        }
      });

</script>

app/views/bookings/_bike_bookings.html.erb
<% booking = @bookings[0] %>
<h2 class="text-center">Bookings for <%= booking.bicycle.brand %> <%= booking.bicycle.model %></h2>
<div class="booking-container">
  <div class="panel panel-form">
    <div class="header">
    </div>
    <% @bookings.each do |booking| %>
      <div class="booking-row">
        <div class="row">
        <div class="col-xs-12 col-sm-4">
          <%= cl_image_tag Bicycle.find(booking.bicycle_id).photo %>
        </div>
          <div class="col-xs-12 col-sm-8">
            <p>Brand: <%= Bicycle.find(booking.bicycle_id).brand %></p>
            <p>Model: <%= Bicycle.find(booking.bicycle_id).model %></p>
            <p>Start date: <%= booking.date_start.strftime("%b %e, %l:%M %p") %></p>
            <p>End date: <%= booking.date_end.strftime("%b %e, %l:%M %p") %></p>
            <%= link_to "delete", bicycle_booking_path(booking.bicycle, booking), method: "delete", data: {confirm: "Are you sure"}, :class => "btn btn primary booking-button smaller-btns" %>
          </div>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<%= simple_form_for [@bicycle, @booking] do |f| %>
  <%= f.input :date_start %>
  <%= f.input :date_end %>
  <div class="form-group">
    <label class="form-control-label text optional" for="bicycle_description"></label>
  <%= f.submit class: "update-booking-btn" %>
  </div>
<% end %>

app/views/bookings/bicycle_bookings.html.erb
<% if @bookings.empty? %>
  <%= render 'layouts/components/no_bookings_page' %>
<% else %>
  <%= render 'bike_bookings' %>
<% end %>

app/views/bookings/edit.html.erb
<div class="vertical-alignment">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <div class="panel panel-form">
      <div class="header">
        <p>Update</p>
      </div>
      <%= render 'form', bicycle: @bicycle, booking: @booking %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<ul>
  <% @bookings.each do |booking| %>
    <li>
      <%= cl_image_tag Bicycle.find(booking.bicycle_id).photo %>
      <p>Brand: <%= Bicycle.find(booking.bicycle_id).brand %></p>
      <p>Model: <%= Bicycle.find(booking.bicycle_id).model %></p>
      <p>Start date: <%= booking.date_start %></p>
      <p>End date: <%= booking.date_end %></p>
      <%= link_to "delete", bicycle_booking_path(booking.bicycle, booking), method: "delete", data: {confirm: "Are you sure"} %></li>
    </li>
  <% end %>
</ul>

app/views/bookings/new.html.erb
<div class="vertical-alignment">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <div class="panel panel-form">
      <div class="header">
        <p>Book now</p>
      </div>
      <%= render 'form', bicycle: @bicycle, booking: @booking %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container container-form">
<div class="row">
    <div class="panel panel-form">
      <div class="col-xs-12 col-sm-4">
        <h3>Booking details</h3>
  <!--   <div class="side-by-side">
      <div class="booking-info"> -->
        <div class="booking-details">
          <p><strong>Brand: </strong><%= Bicycle.find(@booking.bicycle_id).brand %></p>
          <p><strong>Model: </strong><%= Bicycle.find(@booking.bicycle_id).model %></p>
          <p><strong>Start Date: </strong><%= @booking.date_start.strftime("%d/%m/%Y at %l %p") %></p>
          <p><strong>End Date: </strong><%= @booking.date_end.strftime("%d/%m/%Y at %l %p") %></p>
          <p><strong>Total Price: </strong>£<%= @price %></p>
            <%= link_to "Go to your bookings", user_bookings_path, :class => "btn btn primary booking-button" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-8">
          <%= cl_image_tag Bicycle.find(@booking.bicycle_id).photo, class: "bicycle-img" %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/user_bookings.html.erb
<h2 class="text-center">My bookings</h2>
<div class="booking-container">
  <div class="panel panel-form">
    <div class="booking-row">
    <% @bookings.each do |booking| %>
      <div class="row align-booking-info">
        <div class="col-xs-12 col-sm-4">
          <%= cl_image_tag Bicycle.find(booking.bicycle_id).photo %>
        </div>
        <div class="col-xs-12 col-sm-8">
              <p>Brand: <%= Bicycle.find(booking.bicycle_id).brand %></p>
              <p>Model: <%= Bicycle.find(booking.bicycle_id).model %></p>
              <p>Start date: <%= booking.date_start.strftime("%b %e, %l:%M %p") %></p>
              <p>End date: <%= booking.date_end.strftime("%b %e, %l:%M %p") %></p>
            <%= link_to "edit", edit_bicycle_booking_path(booking.bicycle, booking), :class => "btn btn primary booking-button smaller-btns" %>
            <%= link_to "delete", bicycle_booking_path(booking.bicycle, booking), method: "delete", data: {confirm: "Are you sure"}, :class => "btn btn primary booking-button smaller-btns" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>WantToRide</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_pack_tag "map" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/components/in_navbar.html.erb' %>
    <% else %>
      <%= render 'layouts/components/out_navbar.html.erb' %>
    <% end %>
    <% unless (action_name == "index" && controller_name == "bicycles") %>
      <div class="fake-navbar"></div>
    <% end %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
  <script>
    function initUpdateNavbarOnScroll() {
      const banner = document.querySelector('.banner');
      const navbar = document.querySelector('.navbar-wagon');
      console.log(banner)
      console.log(navbar)
      if (banner) {
        if (navbar) {
          window.addEventListener('scroll', () => {
            if (window.scrollY > 400 ) {
              navbar.classList.add("navbar-wagon-white");
            } else {
              navbar.classList.remove('navbar-wagon-white');
            }
          });
        }
      } else {
        navbar.classList.add('navbar-wagon-white');
      }
    }
    initUpdateNavbarOnScroll()
  </script>
</html>

app/views/layouts/components/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://res.cloudinary.com/dsjm0qvdj/image/upload/v1542043604/stangolfcourse.jpg');">
  <div class="banner-content">
    <h1>Find your perfect bike to rent</h1>
      <%= render 'layouts/components/search.html.erb' %>
  </div>
</div>

app/views/layouts/components/_card.html.erb
<div class="container">
  <div class="row">
    <% @bicycles.each do |bicycle| %>

      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path (bicycle.photo.filename.nil? ? "" : bicycle.photo) %>);">
          <div class="card-model">
            <%= bicycle.brand %> <%= bicycle.model %>
            <p>£<%= bicycle.price %>/hr</p>
          </div>
          <div class="card-description">
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star"></span>
            <br>
          </div>
          <%= link_to "", bicycle_path(bicycle), class: "card-link"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/components/_date_picker.html.erb
<div class = "date_container">
  <div class="form-wrapper" style="width: 300px;">
    <%= simple_form_for([@bicycle, @booking], method: "post") do |f| %>
      <%= f.input :date_start, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :date_end, as: :string, required: false, input_html: {class: "datepicker"} %>
      <h3 id ="price_text">Total Price: <span id="currency" class="hidden">£</span><span id="total-price"></span></h3>
      <%= f.submit 'Book', class: "btn btn primary booking-button hidden", id: "book-btn" %>
    <% end %>
  </div>
</div>

app/views/layouts/components/_in_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
   <p>WantToRide</p>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <div class="dropdown">
        <p class="navbar-wagon-link navbar-wagon-item dropdown-toggle", id="navbar-lender-menu" data-toggle="dropdown">Lender</p>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to("Lend a bike", new_bicycle_path, method: "get") %></li>
          <li><%= link_to("My bikes", my_bikes_path, method: "get") %></li>
        </ul>
    </div>

    <%= link_to("Bookings", user_bookings_path, method: "get", class: "navbar-wagon-link navbar-wagon-item") %>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">

        <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", data: {toggle:"dropdown"} %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to("Edit profile", edit_user_registration_path, method: "get") %></li>
          <li><%= link_to("Log out", destroy_user_session_path, method: "delete") %></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to("Lend a bicycle", new_bicycle_path, method: "get") %></li>
        <li><%= link_to("My bikes", my_bikes_path, method: "get") %></li>
        <li><%= link_to("Edit profile", edit_user_registration_path, method: "get") %></li>
        <li><%= link_to("Bookings", user_bookings_path, method: "get", class: "navbar-wagon-link navbar-wagon-item") %></li>
        <li><%= link_to("Log out", destroy_user_session_path, method: "delete") %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/components/_my_bike.html.erb
<div class="booking-buttons">
  <%= link_to "Edit bicycle", edit_bicycle_path, class: "btn btn primary booking-button" %><br>
</div>
<div class="booking-buttons">
  <%= link_to "Bookings for this bike", bicycle_bookings_all_path(@bicycle), class: "btn btn primary booking-button" %><br>
</div>
<div class="booking-buttons">
  <%= link_to "Delete bicycle", bicycle_path, method: "delete", class: "btn btn primary booking-button-delete" %><br>
</div>

app/views/layouts/components/_no_bookings_page.html.erb
<% bicycle = Bicycle.find(params[:bicycle_id]) %>
<div class="white-bar">
  <div class="simple-header">
    <h1 class="text-center">You don't have any bookings for <%= bicycle.brand %> <%= bicycle.model %></h1>
    <h4 class="text-center"><%= link_to "Back", :back %></h4>
  </div>
</div>

app/views/layouts/components/_out_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
   <p>WantToRide</p>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to("Lend a bike", new_bicycle_path, method: "get", class: "navbar-wagon-link navbar-wagon-item") %>
    <%= link_to("Sign up", new_user_registration_path, method: "get", class: "navbar-wagon-link navbar-wagon-item") %>
    <%= link_to("Log in", new_user_session_path, method: "get", class: "navbar-wagon-link navbar-wagon-item") %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to("Lend a bicycle", new_bicycle_path, method: "get") %></li>
        <li><%= link_to("Sign up", new_user_registration_path, method: "get") %></li>
        <li><%= link_to("Log in", new_user_session_path, method: "get") %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/components/_search.html.erb
<div class="search-bar">
    <!--   <form action="/bicycles-search" method="get">
        <input type="search" class="search-input" q="bicycle-search">
        <input type="submit" class="search-submit" value="Search">
      </form> -->
      <%= form_tag bicycles_search_path, method: "get" do %>
        <%= text_field_tag :query, "", placeholder: "Let's ride", class: "search-input" %>
        <%= submit_tag "Search", class: "search-submit" %>
      <% end %>
    </div>

app/views/layouts/components/_sidebar.html.erb
  <div class="sidebar">
    <div class="main">
      <%= link_to 'Edit Profil', '/' %>
      <%= link_to 'Photos', '/' %>
      <%= link_to 'Reviews', '/' %>
      <%= link_to 'Trust and Verification', '/' %>
    </div>
  </div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>